# Generated by Django 4.2.6 on 2023-10-07 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userregistration',
            name='times_logged_in',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
