# Generated by Django 4.2.6 on 2023-10-07 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_userregistration_times_logged_in'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userregistration',
            name='otp',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
