# Generated by Django 4.2.6 on 2023-10-07 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_alter_userregistration_otp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userregistration',
            name='role',
            field=models.CharField(blank=True, choices=[('principal', 'Principal'), ('teacher', 'Teacher'), ('student', 'student')], max_length=255, null=True),
        ),
    ]
