# Generated by Django 4.2.6 on 2023-10-07 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_alter_userregistration_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userregistration',
            name='times_logged_in',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
