# Generated by Django 4.2.6 on 2023-10-09 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_principal_delete_userblockhistory_teacher_principal'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='principal',
        ),
        migrations.AddField(
            model_name='principal',
            name='students',
            field=models.ManyToManyField(blank=True, related_name='principals', to='myapp.student'),
        ),
        migrations.AddField(
            model_name='principal',
            name='teachers',
            field=models.ManyToManyField(blank=True, related_name='principals', to='myapp.teacher'),
        ),
    ]
