# Generated by Django 4.2.6 on 2023-10-10 07:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0015_alter_student_teacher'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='principal',
            name='students',
        ),
        migrations.RemoveField(
            model_name='principal',
            name='teachers',
        ),
        migrations.AddField(
            model_name='student',
            name='printcipal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='student_pricipal', to='myapp.principal'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='printcipal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='teacher_principal', to='myapp.principal'),
        ),
        migrations.AlterField(
            model_name='student',
            name='teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='myapp.teacher'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='subjects',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='teachers', to='myapp.subject'),
        ),
    ]
