# Generated by Django 4.2.6 on 2023-10-10 07:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0016_remove_principal_students_remove_principal_teachers_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='printcipal',
            new_name='principal',
        ),
        migrations.RenameField(
            model_name='teacher',
            old_name='printcipal',
            new_name='principal',
        ),
    ]
